### ISSUE TITLE
draggable not works

### ISSUE THREAD

**Issue by Tastaturberuf** [hofff/contao-calendarfield#25]
https://github.com/terminal42/contao-calendarfield/blob/master/FormCalendarField.php#L77

remove the single ticks.

**Comment by cliffparnitzky** [comment]
@frontendschlampe I think we can close this issue, because the jQuery version doesn't support any Drag&Drop. What do you think.

**Comment by frontendschlampe** [comment]
yes ... we will do so ... it's also a long time ago ;-)
