### ISSUE TITLE
set value property after choose a date

### ISSUE THREAD

**Issue by AryaSvitkona** [hofff/contao-calendarfield#26]
Hi Guys,
Actually the html attribute "value" is not set when I choose a date (see screenshot below).
So it's impossible to work further with that value/date (own jQuery script).

Is there a way I can fix that by myself or do you do that in your next push?
cheers,
Arya_Svitkona
![bildschirmfoto 2015-10-26 um 16 55 11](https://cloud.githubusercontent.com/assets/1257375/10734400/62e1da20-7c03-11e5-91e5-ddad8a0e9507.jpg)

**Comment by aschempp** [comment]
The date picker is an external javascript provided by Contao core, so there's not much we can do about that functionality. You should check on the datepicker script.

**Comment by AryaSvitkona** [comment]
Thank you!
So if I find a workaround I will let you know.

**Comment by aschempp** [comment]
Thanks!
