### ISSUE TITLE
The field for date format is obsolet

### ISSUE THREAD

**Issue by cliffparnitzky** [hofff/contao-calendarfield#29]
There is no good reason to enter a custom date format. The format of the page should be used.

So, remove the field.

**Comment by aschempp** [comment]
That was a feature request once upon a time. Especially useful if your output date has letters (eg. Month name).

**Comment by cliffparnitzky** [comment]
@frontendschlampe have a lokk at the comment above ... maybe this could be a reason!!!

**Comment by frontendschlampe** [comment]
ah ... ok ... but then there should be a fallback for global settings.

**Comment by backbone87** [comment]
Bin dafür das beizubehalten.

**Comment by cliffparnitzky** [comment]
Keep the field and close the discussion.
