### ISSUE TITLE
Widget template

### ISSUE THREAD

**Issue by EDsolution** [hofff/contao-calendarfield#32]
Hi. The template should use .widget or table structure when generated in template.

Now if you use Tabless form all inputs and labels are  in .widget but this has no parent div.

**Comment by cliffparnitzky** [comment]
I don't understand. The template is exactly the same as the one for the normal textfield. And the CSS Classes are `widget widget-text widget-calendar`.

**Comment by EDsolution** [comment]
My mistake. Saw than that it use form_widget.html5 template where tabless doesn't have parent.

**Comment by cliffparnitzky** [comment]
Okay, thanks for the answer.
