### ISSUE TITLE
Bildgröße beim eigenen Icon hinzufügen

### ISSUE THREAD

**Issue by k-webdesign** [hofff/contao-calendarfield#35]
Hi,

wäre es möglich beim eigenen Kalender-Icon die Bildgrößenauswahl aus dem Core hinzuzufügen? Aktuell muss man das Icon entweder immer passend hochladen oder per CSS skalieren. 

Das wäre ein tolles Feature :)

VG Kim

**Comment by cliffparnitzky** [comment]
Available with version 4.0.0 since f265e978bb5bf424730302755ec0e73b02cd72f1
