### ISSUE TITLE
Contao 4.4.1

### ISSUE THREAD

**Issue by ghost** [hofff/contao-calendarfield#38]
Funktioniert unter Contao 4.4.1 mit Contao-Manager leider nicht. Ist geplant, die Erweiterung für Contao 4 nutzbar zu machen?

**Comment by cliffparnitzky** [comment]
Konkret geplant ist es aktuell nicht. Wenn es erfolgreiche Tests gibt, kann man das relativ flott umsetzen.

@jewo5 Kannst du die Extension manuell installieren und testen und das Ergebnis hier preisgeben?

**Comment by jewo5** [comment]
Hatte ich schonmal gemacht.
Ich musste nur (weiss leider nicht mehr genau, wo) die Pfade für jquery anpassen und dann lief es, soweit ich es getestet hatte. Leider habe ich die Contao-Installation nicht mehr - das war nur eine Testinstallation.

**Comment by jewo5** [comment]
falschen Knopp erwischt!

**Comment by Schmidty2** [comment]
+1

**Comment by jewo5** [comment]
Ich habe mich jetzt nochmal damit befasst:
Habe in der FormCalendarField.php die Zeilen 74, 75, 76 wie folgt geändert:

`$GLOBALS['TL_JAVASCRIPT'][] = TL_ASSETS_URL . 'assets/jquery-ui/js/jquery-ui.min.js';
    $GLOBALS['TL_JAVASCRIPT'][] = TL_ASSETS_URL . 'assets/hofff/calendarfield/jquery.ui.datepicker/1.11.4/jquery.ui.datepicker.min.js';
    $GLOBALS['TL_JAVASCRIPT'][] = TL_ASSETS_URL . 'assets/hofff/calendarfield/jquery.ui.datepicker/1.11.4/i18n/jquery.ui.datepicker-' . $objPage->language . '.js';`

Damit funktioniert es für mich so, wie ich es will. Das CSS für den Kalender habe ich mir selber geschrieben und brauche deshalb Zeile 70 nicht.

**Comment by Schmidty2** [comment]
Hallo,
mit oben genannten Anpassungen funktioniert das Auswahlfeld, aber das CSS für den Datepicker wird nicht geladen.

Im Firefox 55.0.2 wird auch das Kalender-Icon des Datepickers gar nicht angezeigt.

Hier ein Screenshot aus meiner FormCalendarField.php und ein Screenshot wie das Ganze im Frontend aussieht.

![img_0664](https://user-images.githubusercontent.com/2067428/29589631-419cd810-8796-11e7-818e-d2179083aeef.PNG)
![img_0666](https://user-images.githubusercontent.com/2067428/29589632-41bed7e4-8796-11e7-9901-80a4d4bcdaa7.PNG)

**Comment by jewo5** [comment]
Hi!
Meine Angaben waren eigentlich mehr für cliffparnitzky gedacht, damit er weiss, das es grundsätzlich funktioniert. Ich bin auch kein Entwickler, sondern habe es mir nur so hingefrickelt, wie es für mich funktioniert. Hast du in den Einstellungen des Kalenderfelds das CSS angehakt? CSS wäre aber kein Problem, das kann man ja selber schreiben. Im aktuellen FF habe ich es gerade getestet - bei mir funktioniert es.

**Comment by cliffparnitzky** [comment]
@Schmidty2 bitte mal eine E-Mail an contao@cliff-parnitzky.de schreiben

**Comment by cliffparnitzky** [comment]
Closed with 29d666a19be836a4e8a29eaa091547890d82da1c

**Comment by SGehle** [comment]
Der CSS-Pfad ist leider noch falsch, wenn man die Datei lokal einbindet:
Dateiname: jquery-ui.datepicker.css

https://github.com/hofff/contao-calendarfield/blob/25ce7a3f321f9cc9abb446ce024f9f3df8281dcb/CT_ROOT/system/modules/hofff_calendarfield/forms/FormCalendarField.php#L74

**Comment by cliffparnitzky** [comment]
@SGehle stimmt

**Comment by cliffparnitzky** [comment]
Woll be obsolet with version 4.0.0
