### ISSUE TITLE
Calendarfield funktioniert nicht, wenn Formular 2x auf einer Seite eingebunden wird

### ISSUE THREAD

**Issue by m-werk** [hofff/contao-calendarfield#39]
Hallo, ich musste ein Formular 2x auf einer Seite einblenden. Jetzt hab ich das Problem, dass beim 1. Formular das calenderfield funktioniert, aber beim 2. Formular nicht mehr.

Ich hab folgende Info hierzu (wurde mir im Contao-Forum so gesagt):
> Der Datepicker sollte lieber mit einem allgemeinen Selector initialisiert werden, statt auf #ctrl_ zu gehen.

Wäre dies lösbar?

**Comment by cliffparnitzky** [comment]
Wie im Forum erklärt, ist die Antwort nicht korrekt und somit nicht nutzbar. 
Dein Anwendungsfall ist recht speziell und nicht mit einer einfachen Umsetzung lösbar.

Wenn es keine Option ist, das Formular zu kopieren, muss was programmiert werden. Das kannst müsstest du dann entsprechend beauftragen.
