### ISSUE TITLE
Contao 4.4.6 Ladefehler JQuery-Datei

### ISSUE THREAD

**Issue by green-pixelbox** [hofff/contao-calendarfield#40]
Hallo. In Contao 4.4.6 wird die Javascript-Datei
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1.1/themes/smoothness/jquery-ui.css">
nicht geladen. Der Link, welcher eingefügt wird, wirft eine 404 raus. Zudem ist das Styling des Kalenders zerschossen. In Contao 4.4.4 funktionierte das Modul noch.

**Comment by cliffparnitzky** [comment]
Hier im Forum gibt es eine Erklärung und Lösung dazu: https://community.contao.org/de/showthread.php?68246-Calendarfield-Datepicker-funktioniert-nach-aktuellem-Update-nicht-mehr&p=452255&viewfull=1#post452255
