### ISSUE TITLE
Possible to configure a date range?

### ISSUE THREAD

**Issue by Clex1o1** [hofff/contao-calendarfield#41]
I don't find something like documentation for this extension. So my question is, you use the jQuery UI datepicker plugin, this plugin provide the option to define a date range with 2 fields. 
Is there any option or solution to do this with your plugin?

**Comment by cliffparnitzky** [comment]
Currently not. This has to be added.

**Comment by frontendschlampe** [comment]
We are currently completely rewriting the extension and will use https://flatpickr.js.org in the future. Through the revision you can then easily set the desired options in the template https://flatpickr.js.org/options/

If you want to have it as a selection in the backend, then I will gladly make you an offer. Send me an email if needed.
