### ISSUE TITLE
fire onSelect event

### ISSUE THREAD

**Issue by GMTeams** [hofff/contao-calendarfield#44]
Usually I would call the calendar within a div with some id, e.g.:

`<div id="calendar"></div>`

```
$(document).ready(function () {
    $("#calendar").datepicker({
        onSelect: function () {
            // do something
        }
    });

});
```

But that's not working because the calendar applies into HTML body.
How can I fire the event?

Thanks!

**Comment by cliffparnitzky** [comment]
Due to the change to flatpickr with version 4.0.0 this not longer relevant. Please refere to the docs: https://flatpickr.js.org/events/
