### ISSUE TITLE
jQuery lokal einbinden

### ISSUE THREAD

**Issue by tinokramm** [hofff/contao-calendarfield#46]
Hallo.

Aus DSGVO-Gründen wäre es gut, wenn das jQuery für das Theme auch lokal eingebunden werden kann. Aktuell wird für das jQuery ein CDN benutzt, was datenschutzrechtlich schwierig ist.

Eine andere Alternative wäre ein eigenes Standard-Theme für den Kalender. Aktuell scheint es kein Theme zu geben, wenn jQuery deaktiviert wird.

Beste Grüße

Tino

**Comment by githuppi** [comment]
Hallo Leute, habt ihr die Issue noch auf dem Zettel?

Wäre echt super wenn es dazu mal eine Auskunft gäbe ob und wann es möglich ist, dass jQuery lokal eingebunden werden kann. Das ist aus DSGVO-Gründen wichtig.

Freue mich auf eine Rückmeldung!

**Comment by githuppi** [comment]
Hallo zusammen,
gibt's hier in Hinblick auf das lokale Einbinden von jQuery schon Neuigkeiten?

**Comment by cliffparnitzky** [comment]
Changed to flatpickr since 15d352d94476df58e04f9d7d6d70b4db5757ca7b
