### ISSUE TITLE
minDate & maxDate

### ISSUE THREAD

**Issue by rike01** [hofff/contao-calendarfield#49]
Ich glaube die Frage gab es schon aber ist es möglich FormCalendarField.php (Contao 4.9) so anzupassen, dass nur ein bestimmter Zeitraum zur Auswahl möglich ist? (Bspw. 19.11.2021-31.12.2021)
Danke, lg Rike

**Comment by frontendschlampe** [comment]
Wir überarbeiten die Erweiterung gerade komplett und werden zukünftig auf https://flatpickr.js.org setzen. Durch die Überarbeitung kannst du dann ganz einfach im Template die gewünschten Optionen setzen https://flatpickr.js.org/options/

Wenn du es als Auswahl im Backend haben möchtest, dann mache ich Dir gern ein Angebot. Schick mir dazu bei Bedarf eine E-Mail.
