### ISSUE TITLE
Zusätzliche Uhrzeitauswahl updatesicher konfigurieren

### ISSUE THREAD

**Issue by rm-medienagentur** [hofff/contao-calendarfield#53]
Hallo,
ich würde gerne beim Datepicker zusätzlich auch die Uhrzeit auswählbar machen (flatpicker lässt das mit der Konfiguration "enableTime: true" zu). Ich finde diese Konfigurationsmöglichkeit in der JS-Datei "flatpickr.js" bzw. "flatpickr.min.js" im Installationsordner /vendor/hofff/contao-calendarfield/src/Resources/public/flatpickr
Eine Änderung dieser Dateien ist aber meines Wissens nach nicht updatesicher. Gibt es eine Möglichkeit, die Konfiguration auch im Template unterzubringen oder irgendwo anders (updatesicher) eine zusätzliche config-Datei abzulegen, die die "flatpickr.min.js" überschreibt?

Ich frage deshalb nach, weil ich das alte Plugin in einer Contao 3.5-Installation im Einsatz habe und nun ein Update auf 4.9 ansteht. Damals war diese Funktion der Uhrzeitauswahl standardmäßig mit dabei - beim neuen Plugin finde ich aber nichts dazu in der Readme.

_Plugin im Einsatz unter Contao 4.9.27_

P.S. optimal wäre natürlich eine Optionswahl "Uhrzeitauswahl aktivieren" im Contao Backend-Modul, das diese Änderung in der Config ändert.

**Comment by cliffparnitzky** [comment]
Einfach rein damit ins Template. Vlt. danach: https://github.com/hofff/contao-calendarfield/blob/master/src/Resources/contao/templates/forms/form_calendarfield.html5#L49

Ansonsten wie geschrieben gern für Usability Improvements die Beauftragung mit @frontendschlampe abstimmen.

**Comment by frontendschlampe** [comment]
Ich glaube, dafür braucht es keine Templateanpassung. Wir haben doch das Feld "individuelle Konfiguration" eingeführt. Da können die entsprechenden Anweisungen rein. Ich habe das schon mal in irgendeinem Projekt probiert, aber ich finde es auf die schnelle nicht. Die Optionen sind hier: https://flatpickr.js.org/options/

**Comment by cliffparnitzky** [comment]
Stimmt. Hab ich schon wieder vergessen 🤕
