### ISSUE TITLE
Warning: Undefined array key "d.m.Y"

### ISSUE THREAD

**Issue by jaynoe** [hofff/contao-calendarfield#56]
- PHP 8.1
- Contao 4.13.14

Execptions:
`vendor/hofff/contao-calendarfield/src/Resources/contao/forms/FormCalendarField.php:239`
`vendor/hofff/contao-calendarfield/src/Resources/contao/forms/FormCalendarField.php:147`

I think this is appears only in PHP 8 and in Contao DEV-Mode.

**Comment by cliffparnitzky** [comment]
Can also confirm `vendor/hofff/contao-calendarfield/src/Resources/contao/forms/FormCalendarField.php:106`
